### ISSUE TITLE
Display bug with WYMeditor, the iframe takes more space than it should

### ISSUE THREAD

**Issue by MadWagon** [refinery/refinerycms#1425]
don't know how to tackle this as it generated by the wymeditor javascript (I assume)

http://madwagon.co/system/images/BAhbBlsHOgZmSSIwMjAxMi8wMy8wOS8wMV80NF8xM185MTVfV3ltZWRpdG9yX2Vycm9yLmpwZwY6BkVU/Wymeditor-error.jpg

Code (generated by Refinery), enclosed in an additional div and form

```
<div id="homepage">
      <%= f.fields_for :home_page do |f_home| -%>

      <%= render '/refinery/admin/error_messages',
                  :object => @site.home_page,
                  :include_object_name => true %>

      <div class='field'>
        <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
          <ul id='page_parts'>
            <% [:description].each_with_index do |part, part_index| %>
              <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
                <%= link_to t("#{part}", :scope => "activerecord.attributes.refinery/sites/home_page", :default => part.to_s.titleize), "##{part}" %>
              </li>
            <% end %>
          </ul>
          <div id='page_part_editors'>
            <% [:description].each do |part| %>
              <div class='page_part' id='<%= part %>'>
                <%= f_home.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
              </div>
            <% end %>
          </div>
        </div>

      </div>
```

**Comment by ttmthanh** [comment]
I got this bug too :(( Please help me

**Comment by evenreven** [comment]
I had a similar, but not identical, issue. My experience is that customising the wymeditor javascript is very brittle and that an override is very likely to break the editor layout in some form. 

That's not exactly a bug, per se. More a limitation.

For instance, I added a button for inserting iframe snippets in the postInit part of admin.js, and it broke the entire html editing window and page images tab because the editor was suddenly fixed size. I needed another override to fix it.

In my case I had to do:

`document.querySelector('.field.hide-overflow').style.height = 'auto';`

(It would look better if I used jquery like the rest of the file, but I only know vanilla js.) 

My general advice would be look for whether you can fix the issue with css or js in dev tools. If you can, you can add javascript at the end of the postInit part. That's barely even advice, but it's what I had to do.

**Comment by ttmthanh** [comment]
@parndt Can you help our about this bug? I try delete all javascript and css but this bug still display...

**Comment by evenreven** [comment]
I'm not parndt, but if you have the exact same issue, then the solution is outlined above. If you have the issue I had (with part of the editor being hidden due to fixed size and hidden overflow), the solution is also outlined for you. 

Either way, you have to give more information than bumping a decade-old closed issue thread if you want help.

**Comment by parndt** [comment]
> My general advice would be look for whether you can fix the issue with css or js in dev tools. If you can, you can add javascript at the end of the postInit part. That's barely even advice, but it's what I had to do.

I think that's very solid advice :smile:

thanks for the help on this issue @evenreven ❤️ 💜 💛 💚

**Comment by ttmthanh** [comment]
@evenreven I embed in WYMeditor, but when I preview pages it does not display. I have put a div tag to mark it but inside that div there is nothing. I think it's WYMeditor compiler problem because I removed all javascript and still got the error. Do you need images from this?

**Comment by ttmthanh** [comment]
@evenreven I use jquery, javascript
