### ISSUE TITLE
Handling preview of pages with skip_to_first_child = true missing / wrong behavior

### ISSUE THREAD

**Issue by mattherick** [refinery/refinerycms#2707]
If I have a page with skip_to_first_child = true and click on "preview" in the admin section I don´t get the expected result. In the frontend I would be redirected to the first child, but in the preview I see the current page - in my opinion this is not the correct behavior - what do you think? and does following make sense for you?
```ruby
Refinery::Pages::Admin::PreviewController.class_eval do
  protected
  def find_page
    if @page = Refinery::Page.find_by_path_or_id(params[:path], params[:id])
      # Preview existing pages
     @page.attributes = params[:page]
    elsif params[:page]
      # Preview a non-persisted page
      @page = Page.new params[:page]
    end
    # added these lines
    @page = @page.children.first if @page.skip_to_first_child
    @page
  end
end
```
But the URL is also not correct with adding the line..

**Comment by parndt** [comment]
@refinery/collaborators yo, opinions?

**Comment by gwagener** [comment]
Seems reasonable. If you want to preview this page you can just untick skip to first child.

The only place I can see it being confusion is if someone who doesn't know the page skips to the first child makes some changes and previews it because the advanced options won't have automatically displayed. Even then it would only be an issue if it's not obvious what page they're viewing. It's probably overkill to add some JavaScript that changes the button text when the skip to first child box is ticked.

**Comment by bricesanchez** [comment]
I never use preview feature but for me it should show the current page and not redirect it if the option `skip_to_first_child ` is set to true. 

I will prefer to have a warning in my preview template who says : `This page use the option "Skip to first child" and will never be displayed to guests users.`

**Comment by parndt** [comment]
@bricesanchez do you care to implement it?

**Comment by bricesanchez** [comment]
Yep.

**Comment by bricesanchez** [comment]
Please follow the PR #3168
