### ISSUE TITLE
More versioning?

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#3016]
Why you don't use more versions? It would be better to manage refinerycms versions in Gemfile... Why is 3.0 so long here? 

*Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.*
[Source: http://semver.org/]

E.g. after commiting changes with gem refinerycms-devise-authentication there should be version 4.0, because of incompatibility with version before...

**Comment by bricesanchez** [comment]
IMHO the main goals of 3.0 was to decouple Refinery CMS from devise and an update to Rails 4.0. So we are closed to be able to release a 3.0 version. 

The master branch of Refinery CMS github is recommended for early adopters

refinerycms-devise-authentication is a new gem created for 3.0+, there is no incompatibility before 3.0 because it's not used.

But you're right, we should probably improve our process deploy more releases on rubygems.

**Comment by prokopsimek** [comment]
*"refinerycms-devise-authentication is a new gem created for 3.0+, there is no incompatibility before 3.0 because it's not used."*
- but RefineryCMS "3.0" is since this merge incompatible with RefineryCMS version "3.0" revision e.g. "6a57f0e5dfe82e03c3d27f8027c8da39704bd36c". Because of this I think, it should be another version...

**Comment by parndt** [comment]
Just use Bundler to lock to the ref before the change. It's hard to develop software, especially open source, and using versions that are not on rubygems come with fewer guarantees.

**Comment by ghoppe** [comment]
I recognize that when we develop on master, we can expect major changes and no guarantees. That said, it would be nice if a post-installation bundler message was added if changes are made that will break a working Refinery CMS install. The *refinerycms-devise-authentication* change bit me and I only found out what needed fixing by checking on Gitter.

**Comment by prokopsimek** [comment]
thx @ghoppe ... I believe you, @parndt , I like refinerycms! I want to give you ideas to do it more developers friendly :)

**Comment by parndt** [comment]
@prokopsimek @ghoppe version 3.0 has been too long in coming due to a great many reasons, not least of which is a lack of personal free time across all of the main developers.  We've also experienced a bit of churn in the core team.

@ghoppe sorry, it seems we forgot to add the refinerycms-authentication-devise extraction to the changelog.  We were just so happy that it was finally in a "ready" state after nearly a year of time had passed on it.

The main reason is simply that we bit off more than we could chew with our vision for 3.0 as we've had a lot of maintenance hassle with things like Devise integration, WYMeditor integation (both of these had severe coupling), and some other unuseful extensions.

So, the long and short of it is that we're nearly 100% happy with the current state of the code and version 3.0.0 is right around the corner.

I accept that it's taken too long to get here and that it is frustrating for people when they run `bundle update` and things suddenly change more than they were expecting them to but we've done what we believed was best for the project from a long term perspective.

Rest assured that once our packages are released to rubygems they follow semver as strictly as we can manage, but this was always considered non-released code with many self-selecting beta testers.

Hopefully things are all settled down now as we only have one more issue (#2931) and two more pull requests for the 3.0 milestone (https://github.com/refinery/refinerycms/pulls?q=is%3Aopen+is%3Apr+milestone%3A3.0)

:heart:
