### ISSUE TITLE
Pages preview doesn't post current body content unless preview button is clicked twice

### ISSUE THREAD

**Issue by steveforse** [refinery/refinerycms#3020]
Verified issue exists on latest commit to master branch (24b521700600d450b23d9dc6ce9c39514611f09d) by generating a new Refinery app.

Verified issue exists on Chrome and IE11.

Steps to reproduce:
1) Install latest Refinery
2) Create/edit page
3) Add new content to body
4) Click preview
5) Preview tab _DOES NOT_ contain latest content
6) Click preview again
7) Preview tab _DOES_ contain latest content

**Comment by parndt** [comment]
A failing test case for this would be A+ excellent!

**Comment by mlinfoot** [comment]
I thought I might help with this and learn some rspec along the way. I've managed to get most of it working, but I've hit an impasse and need some pointers. 

I have two tests, `it 'will not show the preview changes the first time' do` and `it 'will show the preview changes the second time' do`. The first one is working as expected, but the second one fails at the attempt to simulate the second Preview button click with:

    Failure/Error: window = window_opened_by do
    Capybara::WindowError:
      block passed to #window_opened_by opened 0 windows instead of 1

I've created a gist of the [code snippet here](https://gist.github.com/62bff3de3c8c651c7256). After the first `window_opened_by` is closed at line 33, I expected the browser focus to be back at the original new page window and the second `window_opened_by` at line 36 would click the Preview button again. Everything I've tried at this point has failed.

Thoughts? If you see a simple way to make this work, I'll be happy to make a PR.

**Comment by anitagraham** [comment]
Marshall, do you really need the second test? We don't really want people to go to the second click on preview before it works.

What we need - I think - is the first test, but failing. I would suggest that your first test, reworded as below, is all that is needed.  And a fix.
I also split it from the original test which filled the title, and added a context to make that clear. I think.

````ruby
context 'when editing a body part` do
 it 'will show the changes in the preview' do
            visit refinery.admin_pages_path
            find('a', text: 'Add new page').trigger(:click)
        
            page.evaluate_script("WYMeditor.INSTANCES[1].html('<p>Some changes. What they will look like?</p>')")
            window = window_opened_by do
              click_button "Preview"
            end

            expect_window_without_content(preview_content, window: window)

            window.close
          end
  end
````

**Comment by mlinfoot** [comment]
Much better, Anita. Thanks! If we want it to fail now, but pass when the issue is fixed, we should "expect_window_with_content". Like so:

    context 'when editing a body part` do
      it 'will show the changes in the preview' do
        visit refinery.admin_pages_path
        find('a', text: 'Add new page').trigger(:click)
        page.evaluate_script("WYMeditor.INSTANCES[1].html('<p>Some changes. What they will look like?</p>')")
        window = window_opened_by do
          click_button "Preview"
        end
        expect_window_with_content(preview_content, window: window)
        window.close
      end
    end

As for a fix, I'm afraid I wouldn't know where to start :( I hope the test will help, though.

**Comment by michael-misshore** [comment]
I've taken a look at this as well, and I can make the test fail if I place the content into the wymeditor with javascript. If I click the preview button twice in the test, the test pass. However, if I update the page part's form textarea directly, the test pass on the first click. 

I've tried this with a different editor (TinyMCE), and I cannot replicate this issue. This issue seems specific to the wymeditor.

I still don't have a strong handle as to why this works the second time the Preview button is pressed, but hopefully I can devote some more time to it soon.

**Comment by aiomaster** [comment]
Hi, I had this problem too and I think I have found the reason of this behaviour.
The WYMeditor uses an iframe for editing and a hidden field where the content of the editor is synched to, so that the form submission gets the latest content.
There is a magic implemented that binds per default a click handler to buttons having the class 'wymupdate' (you can read the details here: https://wymeditor.readthedocs.io/en/v1.1.1/getting_started/setup.html#quick-start-instructions), that intiializes this sync after such a button is clicked.

The problem now is, that refinery binds a click handler to the preview button, too:
https://github.com/refinery/refinerycms/blob/master/pages/app/views/refinery/admin/pages/_form.html.erb#L47
I think this is needed to change the form action url to the preview url.

The clue is, that this last bound click handler from refinery is fired before the click handler that syncs the WYMeditor content, so you see the old content at the first click, but the second click has your changed content, because the sync was fired at the first click, but too late.

You can influence the order of the click handlers in jquery by changing the way you attach them.
A very quick solution to this problem (that seems to work for me) is to change the click event binding
in https://github.com/refinery/refinerycms/blob/master/pages/app/views/refinery/admin/pages/_form.html.erb#L47
from:
`$("#preview-button").click(function(e) {`
to: 
`$(document).on('click', '#preview-button', function(e) {`

So it is not bound to the element directly but to the document, where it is fired when the event is bubbled up and after the WYMeditor sync event.
Maybe @parndt can fix that in refinery?

**Comment by parndt** [comment]
@aiomaster amazing research. Would you care to open a pull request with that change? I'd like you to get full credit for the patch if it fixes this problem!

**Comment by aiomaster** [comment]
Pull request is there, but without a test to show that this is working.
I tried to use the test code from @mlinfoot but the WYMeditor is not setup in the pages_spec test.
I get the error: `TypeError: undefined is not an object (evaluating 'WYMeditor.INSTANCES[1].html')`
Does somebody know, how to setup the WYMeditor in these tests right?
