### ISSUE TITLE
Navbar in demo-application changes language

### ISSUE THREAD

**Issue by Bergrebell** [refinery/refinerycms#3192]
when clicking on the buttons in the navigationbar the language changes. see screenshot below.
![bildschirmfoto 2016-06-07 um 09 08 52](https://cloud.githubusercontent.com/assets/6041919/15850322/a4b2c7a8-2c97-11e6-86b6-5efc41f6dba9.png)

**Comment by bricesanchez** [comment]
That's a know bug, it happens only on the demo because everybody share the same user as admin : https://github.com/refinery/demo/issues/1

There is a feature request to fix it and to help user to set their preferred language : https://github.com/refinery/refinerycms-authentication-devise/issues/19

Feel free to help us to fix this bug! Thanks!
