### ISSUE TITLE
Can't Install 4.0.3

### ISSUE THREAD

**Issue by carltonsmith** [refinery/refinerycms#3430]
Looking here, the latest version is 4.0.2 but rubygems.org has 4.0.3 and it won't install from the gem. Running...

`gem install refinerycms`

... works as expected, but then trying to create an application fails...

`refinerycms myappname`

results in the following after the bundle completes...

```
        rake    db:create
Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
Couldn't create database for {"adapter"=>"sqlite3", "pool"=>5, "timeout"=>5000, "database"=>"db/development.sqlite3"}
rake aborted!
Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).


Caused by:
Gem::LoadError: can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
```

**Comment by EdSF** [comment]
Disclaimer: I'm a `C#` dev so I'm **not** a Ruby pro by any measure...

Hit this issue in my own install and I've tracked it down to incompatibility with `SQLite 1.4.0` with my installed version of `ActiveRecord 5.1.6.2` - it could be something else in your environment, so was specific to mine. 

This leads to the confusing message about "add gem sqlite3 to your Gemfile" - and while I'm way past my teens, my eyes can still see that _I do have it in my Gemfile with a **specific** version at that_ 
e.g. 
`'gem sqlite3', '1.3.13'` 

Turns out that the Refinery install will modify your Gemfile and and look something like this

```
group :development, :test do  
  gem 'sqlite3'
end, '1.3.13'
```

Note how the version isn't actually discarded during modification (text just inserted) which results in bad syntax. This leads to myriad errors too lengthy to describe.

---
What I've done/hack really:

- monitor the Gemfile as the task progresses (essentially opened in some code editor)
- run `refinery app_name` **again**
- which, afaik, will go through the same process and interactively asks whether you want to _overwrite_ files (correctly)
- At some point, the Gemfile modification process occurs - I believe this will be right before the db processes - migrate, etc. so, you'll have a chancel to correct the Gemfile syntax while the terminal is interactively asking you to overwrite existing files. So correct your Gemfile _before_ allowing the process to overwrite (Y).
- You should (hopefully) see the db processes move forward and your install should be fine

---

Obviously: An easier track would be to ensure that your Gem (versions) play together nicely. I personally do not know what version of ActiveRecord works well with SQLite 1.4.0....what I do know is that at least for `ActiveRecord 5.1.6.2`, it's `SQLite 1.3.13`

---

It would also be helpful if the Refinery process that modifies the Gemfile takes the Gem version into account properly....

Hope this helps....

**Comment by bricesanchez** [comment]
I'm closing this issue, this is not a Refinery issue and sqlite3 should not be used on a real project (only for maintainers, CI or for specific purpose).
